# Generated by Django 5.1 on 2024-09-21 04:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateField()),
                ('plan_no', models.CharField(max_length=10, null=True)),
                ('plan_qty', models.IntegerField()),
                ('pd_line', models.CharField(max_length=10)),
                ('item_group', models.CharField(max_length=10)),
                ('pd_information', models.JSONField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_management.salesorder')),
            ],
        ),
    ]
