# Generated by Django 5.1 on 2024-10-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0004_development_developmentcomment_developmentorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developmentorder',
            name='order_information',
        ),
        migrations.AddField(
            model_name='developmentorder',
            name='base_color',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='developmentorder',
            name='color_code',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developmentorder',
            name='item_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developmentorder',
            name='order_qty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developmentorder',
            name='order_remark',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='developmentorder',
            name='pattern',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developmentorder',
            name='qty_unit',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developmentorder',
            name='spec',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
