# Generated by Django 5.1 on 2024-10-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0005_remove_developmentorder_order_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentorder',
            name='product_group',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
