# Generated by Django 5.1 on 2024-10-11 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0006_developmentorder_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developmentcomment',
            name='development',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_comment_set', to='production_management.development'),
        ),
    ]
