# Generated by Django 5.1 on 2024-09-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, choices=[('PD', 'Production Director'), ('PM', 'Production Manager'), ('PS', 'Production Staff'), ('SD', 'Sales Director'), ('SM', 'Sales Manager'), ('SS', 'Sales Staff')], max_length=3),
        ),
    ]
