# Generated by Django 5.1 on 2024-09-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_profile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ko', '한국어'), ('vn', 'Tiếng Việt')], default='en', max_length=5),
        ),
    ]
