# Generated by Django 5.1 on 2024-09-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_profile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ko', '한국어'), ('vi', 'Tiếng Việt')], default='en', max_length=5),
        ),
    ]
