# Generated by Django 5.1 on 2024-09-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('GW', 'General Worker'), ('VTL', 'Vice Team Leader'), ('TL', 'Team Leader')], default='GW', max_length=3)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(choices=[('BL', 'Boiler'), ('BF', 'Buffing'), ('RC', 'Recovery'), ('DL1', 'Dry Line1'), ('DL2', 'Dry Line2'), ('DL3', 'Dry Line3'), ('DL4', 'Dry Line4'), ('DM', 'Dry Mixing'), ('EB', 'Embossing'), ('ES', 'Environment and Safety'), ('INS', 'Inspection'), ('MT', 'Maintance'), ('PT', 'Printing'), ('PO', 'Production Office'), ('QC', 'Quality Control'), ('RP', 'Release Paper'), ('SM', 'Semi-Material'), ('SP', 'Shipment'), ('ST', 'Stock'), ('WL', 'Wet Line'), ('WM', 'Wet Mixing')], default='PO', max_length=4)),
                ('join_date', models.DateField()),
                ('status', models.BooleanField(null=True)),
            ],
        ),
    ]
