# Generated by Django 5.1 on 2024-09-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='department',
            field=models.CharField(choices=[('BL', 'Boiler'), ('BF', 'Buffing'), ('RC', 'Recovery'), ('DL1', 'Dry Line1'), ('DL2', 'Dry Line2'), ('DL3', 'Dry Line3'), ('DL4', 'Dry Line4'), ('DM', 'Dry Mixing'), ('EB', 'Embossing'), ('ES', 'Environment and Safety'), ('INS', 'Inspection'), ('MT', 'Maintance'), ('PT', 'Printing'), ('PO', 'Production Office'), ('QC', 'Quality Control'), ('RP', 'Release Paper'), ('SM', 'Semi-Material'), ('SP', 'Shipment'), ('ST', 'Stock'), ('WL', 'Wet Line'), ('WM', 'Wet Mixing'), ('WH', 'Warehouse')], default='PO', max_length=4),
        ),
    ]
