# Generated by Django 5.1 on 2025-06-21 00:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production_management', '0007_alter_developmentcomment_development'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_no', models.CharField(max_length=20, unique=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=60, unique=True)),
                ('department', models.CharField(db_index=True, max_length=40)),
                ('user_name', models.CharField(blank=True, max_length=20, null=True)),
                ('ip_lan', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_tailscale', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['department', 'hostname'],
            },
        ),
        migrations.CreateModel(
            name='ColorSwatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt', models.IntegerField(default=0, verbose_name='STT')),
                ('type', models.CharField(choices=[('MG', 'Main'), ('SP', 'Sample')], default='MG', max_length=2, verbose_name='Loại (MG/SP)')),
                ('customer', models.CharField(default='', max_length=200, verbose_name='Khách hàng')),
                ('item', models.CharField(default='', max_length=200, verbose_name='Sản phẩm')),
                ('color', models.CharField(default='', max_length=50, verbose_name='Màu')),
                ('pattern', models.CharField(default='', max_length=100, verbose_name='Mẫu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Last Location')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Last Location Date')),
            ],
            options={
                'ordering': ['stt'],
                'indexes': [models.Index(fields=['customer', 'item', 'color', 'pattern'], name='data_monito_custome_4139a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Delamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dlami_qty', models.IntegerField()),
                ('dlami_information', models.JSONField(null=True)),
                ('line_no', models.CharField(max_length=10)),
                ('dlami_lot', models.CharField(max_length=50, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(auto_now=True, null=True)),
                ('production_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_management.productionplan')),
            ],
        ),
        migrations.CreateModel(
            name='DryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_qty', models.IntegerField()),
                ('pd_information', models.JSONField(null=True)),
                ('line_no', models.CharField(max_length=10)),
                ('ag_position', models.CharField(max_length=50, null=True)),
                ('pd_lot', models.CharField(max_length=50, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(auto_now=True, null=True)),
                ('production_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_management.productionplan')),
            ],
        ),
        migrations.CreateModel(
            name='DryMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mixing_information', models.JSONField(null=True)),
                ('worker_code', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(auto_now=True, null=True)),
                ('production_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_management.productionplan')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_qty', models.IntegerField()),
                ('ins_information', models.JSONField(null=True)),
                ('line_no', models.CharField(max_length=10)),
                ('qty_to_printing', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(auto_now=True, null=True)),
                ('production_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_management.productionplan')),
                ('sales_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_management.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='Printing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_qty', models.IntegerField()),
                ('print_information', models.JSONField(null=True)),
                ('line_no', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(auto_now=True, null=True)),
                ('production_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_management.productionplan')),
                ('sales_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_management.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='WetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_qty', models.IntegerField()),
                ('pd_information', models.JSONField(null=True)),
                ('line_no', models.CharField(max_length=10)),
                ('pd_lot', models.CharField(max_length=50, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(auto_now=True, null=True)),
                ('production_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_management.productionplan')),
            ],
        ),
        migrations.CreateModel(
            name='WetMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mixing_information', models.JSONField(null=True)),
                ('worker_code', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(auto_now=True, null=True)),
                ('production_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_management.productionplan')),
            ],
        ),
        migrations.CreateModel(
            name='ColorSwatchMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=20, verbose_name='Department')),
                ('created_date', models.DateTimeField(verbose_name='Received Time')),
                ('color_swatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='data_monitoring.colorswatch')),
            ],
            options={
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['color_swatch', '-created_date'], name='data_monito_color_s_cadcd1_idx')],
            },
        ),
    ]
