# Generated by Django 5.1 on 2024-09-21 03:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=10)),
                ('seq_no', models.IntegerField()),
                ('order_no', models.CharField(editable=False, max_length=14, unique=True)),
                ('customer_order_no', models.CharField(max_length=100, null=True)),
                ('customer_name', models.CharField(max_length=50)),
                ('order_type', models.CharField(max_length=2)),
                ('order_date', models.DateField()),
                ('rtd', models.DateField()),
                ('etd', models.DateField()),
                ('brand', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=50)),
                ('color_code', models.CharField(max_length=50)),
                ('pattern', models.CharField(max_length=50)),
                ('base_color', models.CharField(max_length=10, null=True)),
                ('spec', models.CharField(max_length=50)),
                ('order_qty', models.IntegerField()),
                ('qty_unit', models.CharField(max_length=10)),
                ('unit_price', models.FloatField()),
                ('currency', models.CharField(max_length=10)),
                ('order_remark', models.TextField(null=True)),
                ('model_name', models.CharField(max_length=100, null=True)),
                ('sample_step', models.CharField(max_length=50, null=True)),
                ('production_location', models.CharField(max_length=50)),
                ('product_group', models.CharField(max_length=10)),
                ('product_type', models.CharField(max_length=50)),
                ('color_name', models.CharField(max_length=50, null=True)),
                ('status', models.BooleanField(null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
