# Generated by Django 5.1 on 2024-09-21 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesOrder',
        ),
    ]
