# Generated by Django 5.1 on 2025-06-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorswatchmovement',
            name='created_by',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Created By'),
        ),
    ]
