# Generated by Django 5.1 on 2024-09-21 06:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_monitoring', '0002_delete_salesorder'),
        ('production_management', '0002_productionplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dlami_qty', models.IntegerField()),
                ('dlami_information', models.JSONField(null=True)),
                ('line_no', models.CharField(max_length=10)),
                ('dlami_lot', models.CharField(max_length=50, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(auto_now=True, null=True)),
                ('production_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_management.productionplan')),
            ],
        ),
        migrations.CreateModel(
            name='DryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_qty', models.IntegerField()),
                ('pd_information', models.JSONField(null=True)),
                ('line_no', models.CharField(max_length=10)),
                ('ag_position', models.CharField(max_length=50, null=True)),
                ('pd_lot', models.CharField(max_length=50, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(auto_now=True, null=True)),
                ('production_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_management.productionplan')),
            ],
        ),
        migrations.CreateModel(
            name='DryMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mixing_information', models.JSONField(null=True)),
                ('worker_code', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(auto_now=True, null=True)),
                ('production_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_management.productionplan')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_qty', models.IntegerField()),
                ('ins_information', models.JSONField(null=True)),
                ('line_no', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(auto_now=True, null=True)),
                ('production_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_management.productionplan')),
            ],
        ),
        migrations.CreateModel(
            name='WetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_qty', models.IntegerField()),
                ('pd_information', models.JSONField(null=True)),
                ('line_no', models.CharField(max_length=10)),
                ('pd_lot', models.CharField(max_length=50, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(auto_now=True, null=True)),
                ('production_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_management.productionplan')),
            ],
        ),
        migrations.CreateModel(
            name='WetMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mixing_information', models.JSONField(null=True)),
                ('worker_code', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(auto_now=True, null=True)),
                ('production_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_management.productionplan')),
            ],
        ),
    ]
