# Generated by Django 5.1 on 2025-06-23 09:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_monitoring', '0002_colorswatchmovement_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorswatch',
            name='created_at',
        ),
        migrations.AddField(
            model_name='colorswatch',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='colorswatch',
            name='epc',
            field=models.CharField(default='', max_length=200, verbose_name='EPC Code'),
        ),
        migrations.AddField(
            model_name='colorswatch',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
