# Generated by Django 5.1 on 2025-06-24 04:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_monitoring', '0003_remove_colorswatch_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorswatch',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
