# Generated by Django 5.1 on 2025-06-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_monitoring', '0004_alter_colorswatch_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorswatch',
            name='epc',
            field=models.CharField(max_length=200, unique=True, verbose_name='EPC Code'),
        ),
    ]
