# Generated by Django 5.1 on 2024-09-25 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_monitoring', '0004_productionlot'),
        ('production_management', '0002_productionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='sales_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_management.salesorder'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='production_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_management.productionplan'),
        ),
    ]
