# Generated by Django 5.1 on 2025-06-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_monitoring', '0005_alter_colorswatch_epc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorswatch',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Màu'),
        ),
        migrations.AlterField(
            model_name='colorswatch',
            name='customer',
            field=models.CharField(max_length=200, verbose_name='Khách hàng'),
        ),
        migrations.AlterField(
            model_name='colorswatch',
            name='item',
            field=models.CharField(max_length=200, verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='colorswatch',
            name='pattern',
            field=models.CharField(max_length=100, verbose_name='Mẫu'),
        ),
        migrations.AlterField(
            model_name='colorswatch',
            name='type',
            field=models.CharField(choices=[('MG', 'Main'), ('SP', 'Sample')], max_length=2, verbose_name='Loại (MG/SP)'),
        ),
    ]
