# Generated by Django 5.1 on 2025-05-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_monitoring', '0005_inspection_sales_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='next_step',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Công đoạn tiếp theo'),
        ),
    ]
