# Generated by Django 5.1 on 2025-06-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_monitoring', '0006_alter_colorswatch_color_alter_colorswatch_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorswatch',
            name='epc',
            field=models.CharField(max_length=200, verbose_name='EPC Code'),
        ),
    ]
