# Generated by Django 5.1 on 2025-05-21 09:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_monitoring', '0006_inspection_next_step'),
        ('production_management', '0007_alter_developmentcomment_development'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_qty', models.IntegerField()),
                ('print_information', models.JSONField(null=True)),
                ('line_no', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(auto_now=True, null=True)),
                ('production_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_management.productionplan')),
                ('sales_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_management.salesorder')),
            ],
        ),
    ]
