# Generated by Django 5.1 on 2025-06-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_monitoring', '0006_inspection_next_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='next_step',
        ),
        migrations.AddField(
            model_name='inspection',
            name='qty_to_printing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
