# Generated by Django 5.1 on 2025-06-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_monitoring', '0007_alter_colorswatch_epc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorswatch',
            name='epc',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='EPC Code'),
        ),
    ]
