# Generated by Django 5.1 on 2025-06-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_monitoring', '0008_alter_colorswatch_epc'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='colorswatch',
            name='data_monito_custome_4139a5_idx',
        ),
        migrations.AlterField(
            model_name='colorswatch',
            name='stt',
            field=models.IntegerField(verbose_name='STT'),
        ),
        migrations.AddIndex(
            model_name='colorswatch',
            index=models.Index(fields=['epc'], name='data_monito_epc_9b7252_idx'),
        ),
    ]
