# Generated by Django 5.1 on 2025-06-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_monitoring', '0009_remove_colorswatch_data_monito_custome_4139a5_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorswatchmovement',
            name='department',
        ),
        migrations.AddField(
            model_name='colorswatchmovement',
            name='hostname',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Hostname'),
        ),
    ]
