# Generated by Django 5.1 on 2025-06-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_monitoring', '0010_remove_colorswatchmovement_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorswatchmovement',
            name='hostname',
        ),
        migrations.AddField(
            model_name='colorswatchmovement',
            name='line_no',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Line No'),
        ),
    ]
