# Generated by Django 5.1 on 2025-06-28 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_monitoring', '0011_remove_colorswatchmovement_hostname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorswatch',
            name='last_seen',
        ),
    ]
