# Generated by Django 5.1 on 2025-07-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_monitoring', '0012_remove_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorswatch',
            name='base_color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Màu Base'),
        ),
    ]
